[package]
name = "cashier-server"
version = "0.1.0"
authors = ["Sun Ziping <sunziping2016@gmail.com>"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.1"
err-derive = "0.2.4"
serde = "1.0.111"
serde_json = "1.0"
shell-macro = { path = "../shell-macro" }
