[package]
name = "cashier-server"
version = "0.1.0"
authors = ["Sun Ziping <sunziping2016@gmail.com>"]
edition = "2018"

[dependencies]
actix-multipart = "0.3.0-alpha.1"
actix-rt = "1.0"
actix-web = "2.0"
bcrypt = "0.8.0"
chrono = { version = "0.4", features = ["serde"] }
clap = "3.0.0-beta.1"
derive_more = "0.99.7"
env_logger = "0.7.1"
err-derive = "0.2.4"
futures = "0.3.5"
jsonwebtoken = "7.1.1"
lazy_static = "1.4.0"
log = "0.4.8"
regex = "1"
rand = "0.7.3"
rpassword = "4.0.5"
serde = { version = "1.0.111", features = ["derive"] }
serde_json = "1.0"
shell-macro = { path = "../shell-macro" }
tokio = { version = "0.2.21", features = ["full"] }
tokio-postgres = { version = "0.5.4", features = ["with-chrono-0_4"] }
validator = "0.10"
validator_derive = "0.10"
